# data parameters
model: DNCNN
train_data_path: /home/yoon/Datasets/DNCNN

model_name: dncnn
save_path: checkpoint/dncnn/
num_classes: 2
epoch: 20
batch_size: 8

# training parameters
cuda: True
gpu_ids: [0]  # set the GPU ids to use, e.g. [0] or [1, 2]
num_workers: 16
print_iter: 5000

input_size: 180
noise: gaussian
lr: 1e-03

